import 'package:hive/hive.dart';

part 'app_settings.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1)
class AppSettings extends HiveObject {
  @HiveField(0)
  bool hasOnboarded;

  @HiveField(1)
  String userName;

  @HiveField(2)
  int challengeLength; // 7, 15, or 30 days

  @HiveField(3)
  bool challengeCompleted;

  AppSettings({
    this.hasOnboarded = false,
    this.userName = 'Friend',
    this.challengeLength = 7,
    this.challengeCompleted = false,
  });
}
