import 'package:hive/hive.dart';

part 'habit.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class Habit extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  String iconName; // e.g., 'gym', 'book', 'water'

  @HiveField(2)
  List<DateTime> completedDays;

  Habit({
    required this.name,
    required this.iconName,
    required this.completedDays,
  });
}
